services:
  sopds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sopds
    environment:
      - PUID=1002
      - PGID=100
      - EXT_DB=True
      - DB_HOST=sopds_db
      - DB_PORT=5432
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - SOPDS_SU_EMAIL=k.ahtoh@gmail.com
      - SOPDS_SU_NAME=${SOPDS_SU_NAME}
      - SOPDS_SU_PASS=${SOPDS_SU_PASS}
      - SOPDS_ROOT_LIB=/library
      - SOPDS_INPX_ENABLE=False
      - SOPDS_LANGUAGE=ru-RU
      - SOPDS_CSRF_TRUSTED_ORIGINS=https://ebook.iahtoh.ru,http://ebook.iahtoh.ru
      - SOPDS_CONVERT_ENABLE=False
      - SOPDS_TMBOT_ENABLE=False
      - CONV_LOG=/sopds/opds_catalog/log
    volumes:
      - /run/media/ahtoh/SSD2/e-book:/library:ro
      - /docker/sopds/log:/sopds/opds_catalog/log
    ports:
      - 8199:8000
    restart: always
    networks:
      - sopds_net

networks:
  sopds_net:
    external: true
