services:
  app:
    build:
      context: .          # ← корень проекта
      dockerfile: Dockerfile
    container_name: sopds
    volumes:
      - .:/workspace
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - DJANGO_SETTINGS_MODULE=sopds.settings
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: sopds_db
    environment:
      POSTGRES_DB: sopds
      POSTGRES_USER: sopds
      POSTGRES_PASSWORD: sopds
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
