# EOPDS — Электронная OPDS Домашняя библиотека
services:
  db:
    image: postgres:15-alpine
    container_name: eopds-db
    environment:
      POSTGRES_DB: eopds
      POSTGRES_USER: eopds
      POSTGRES_PASSWORD: eopds123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eopds -d eopds"]
      interval: 5s
      timeout: 5s
      retries: 5

  eopds:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eopds
    depends_on:
      db:
        condition: service_healthy
    environment:
      - EXT_DB=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=eopds
      - DB_USER=eopds
      - DB_PASS=eopds123
      - EOPDS_SU_NAME=admin
      - EOPDS_SU_EMAIL=admin@eopds.local
      - EOPDS_SU_PASS=admin123
      - EOPDS_ROOT_LIB=/library
      - EOPDS_INPX_ENABLE=True
      - EOPDS_LANGUAGE=ru-RU
      - EOPDS_SERVER_PORT=8000
    volumes:
      - .:/workspace
      - /run/media/ahtoh/SSD2/e-book:/library:ro
    ports:
      - 8000:8000
    restart: unless-stopped

volumes:
  pgdata:
