"""
Django settings for eopds project.

Generated by 'django-admin startproject' using Django 1.9.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os
from collections import OrderedDict

# from django.utils.translation import ugettext_lazy as _
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "m4l1c#nq6*zs!c3ri4dg4(54_7bvrl5uintni6p20tijlaxv!x"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]

# Application definition
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "opds_catalog",
    "eopds_web_backend",
    "django.contrib.admin",
    "django.contrib.staticfiles",
    "constance.backends.database",
    "constance",
]

MIDDLEWARE = [
    "django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    #'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    "opds_catalog.middleware.eopdsLocaleMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    #'django.middleware.cache.CacheMiddleware',
    #'opds_catalog.middleware.FetchFromCacheMiddleware',
]

ROOT_URLCONF = "eopds.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "eopds_web_backend.views.eopds_processor",
            ],
        },
    },
]

WSGI_APPLICATION = "eopds.wsgi.application"

#### eopds DATABASE SETTINGS START ####

# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

# DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.mysql',
#        'NAME': 'eopds',
#        'HOST': 'localhost',
#        'USER': 'eopds',
#        'PASSWORD' : 'eopds',
#        'OPTIONS' : {
#        'init_command': """SET default_storage_engine=INNODB; \
#                       SET sql_mode='STRICT_TRANS_TABLES'; \
#                       SET NAMES UTF8 COLLATE utf8_general_ci; \
#                       SET SESSION TRANSACTION ISOLATION LEVEL READ COMMITTED
#                    """
#         }
#
#
#
#        'OPTIONS' : {
#            'init_command': "SET default_storage_engine=MyISAM;\
#                             SET sql_mode='';"
#        }
#    }
# }

# DATABASES = {
#    'default': {
#    'ENGINE': 'django.db.backends.postgresql_psycopg2',
#    'NAME': 'eopds',
#    'USER': 'eopds',
#    'PASSWORD': 'eopds',
#    'HOST': '', # Set to empty string for localhost.
#    'PORT': '', # Set to empty string for default.
#    }
# }

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "eopds",
        "USER": "eopds",
        "PASSWORD": "eopds123",
        "HOST": "db",
        "PORT": "5432",
    }
}

DEFAULT_AUTO_FIELD = "django.db.models.AutoField"

#### eopds DATABASE SETTINGS FINISH ####

# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LOCALE_PATHS = (os.path.join(BASE_DIR, "eopds/locale"),)

TIME_ZONE = "Europe/Moscow"
USE_I18N = True
USE_L10N = True
USE_TZ = True

CACHE_BACKEND = "locmem://"
CACHE_MIDDLEWARE_KEY_PREFIX = "eopds"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = os.path.join(BASE_DIR, "static_root")
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

CONSTANCE_BACKEND = "constance.backends.database.DatabaseBackend"

CONSTANCE_ADDITIONAL_FIELDS = {
    "language_select": [
        "django.forms.fields.ChoiceField",
        {
            "widget": "django.forms.Select",
            "choices": (("ru-RU", "Russian"), ("en-US", "English")),
        },
    ],
}

CONSTANCE_CONFIG = OrderedDict(
    [
        ("EOPDS_LANGUAGE", ("en-US", _("Select language"), "language_select")),
        (
            "EOPDS_ROOT_LIB",
            ("books/", _("Absolute path to books collection directory")),
        ),
        (
            "EOPDS_BOOK_EXTENSIONS",
            (".pdf .djvu .fb2 .epub .mobi", _("List of managed book files extensions")),
        ),
        ("EOPDS_SCAN_START_DIRECTLY", (False, _("Turn once scanning directly"))),
        ("EOPDS_CACHE_TIME", (1200, _("Pages cache time"))),
        ("EOPDS_TELEBOT_API_TOKEN", ("", _("Telegramm API Token"))),
        (
            "EOPDS_TELEBOT_AUTH",
            (
                True,
                _(
                    "Enable telebot authentication. Test presense telegram username in local users database (case insensetive)."
                ),
            ),
        ),
        ("EOPDS_TELEBOT_MAXITEMS", (10, _("Max items on page"))),
        ("EOPDS_AUTH", (True, _("Enable authentication"))),
        ("EOPDS_ALPHABET_MENU", (True, _("Enable alphabet submenu"))),
        ("EOPDS_DOUBLES_HIDE", (True, _("This flag hides found doublicates"))),
        ("EOPDS_COVER_SHOW", (True, _("This flag activate showing cover of books"))),
        ("EOPDS_SPLITITEMS", (300, _("Max subitems count in alphabet menuitem"))),
        ("EOPDS_MAXITEMS", (60, _("Max items on page"))),
        (
            "EOPDS_TITLE_AS_FILENAME",
            (True, _("Create downloaded filename from book title")),
        ),
        (
            "EOPDS_NOCOVER_PATH",
            (
                os.path.join(BASE_DIR, "static/images/nocover.jpg"),
                _("Path to image file showing for book without embedded cover"),
            ),
        ),
        (
            "EOPDS_FB2SAX",
            (True, _("This flag activate SAX Parser for FB2 instead of lxml.xpath")),
        ),
        ("EOPDS_ZIPSCAN", (True, _("This flag activate zip files scanning"))),
        (
            "EOPDS_ZIPCODEPAGE",
            ("cp866", _("Set codepage for filenames inside zipfile")),
        ),
        (
            "EOPDS_INPX_ENABLE",
            (
                False,
                _(
                    "Enables read metadata from inpx-file (and stop scanning deeper from ipx-file place)"
                ),
            ),
        ),
        (
            "EOPDS_INPX_SKIP_UNCHANGED",
            (True, _("Skip scanning INPX with unchanged size after previous scan")),
        ),
        (
            "EOPDS_INPX_TEST_ZIP",
            (
                False,
                _(
                    "Test avialability zip files listed in INPX before add in collection"
                ),
            ),
        ),
        (
            "EOPDS_INPX_TEST_FILES",
            (
                False,
                _(
                    "Test avialability book files listed in INPX before add in collection"
                ),
            ),
        ),
        ("EOPDS_DELETE_LOGICAL", (False, _("Logical deleting unavialable files"))),
        (
            "EOPDS_SCAN_SHED_MIN",
            ("0", _("sheduled minutes for eopds_scanner (cron syntax)")),
        ),
        (
            "EOPDS_SCAN_SHED_HOUR",
            ("0,12", _("sheduled hours for eopds_scanner (cron syntax)")),
        ),
        (
            "EOPDS_SCAN_SHED_DAY",
            ("*", _("sheduled day for eopds_scanner (cron syntax)")),
        ),
        (
            "EOPDS_SCAN_SHED_DOW",
            ("*", _("sheduled day of weeks for eopds_scanner (cron syntax)")),
        ),
        ("EOPDS_FB2TOEPUB", ("", _("Path to FB2-EPUB (EPUB2) converter program"))),
        ("EOPDS_FB2TOEPUB3", ("", _("Path to FB2-EPUB3 converter program"))),
        ("EOPDS_FB2TOKEPUB", ("", _("Path to FB2-KEPUB (Kobo) converter program"))),
        ("EOPDS_FB2TOMOBI", ("", _("Path to FB2-MOBI/AZW8 (Kindle) converter program"))),
        ("EOPDS_FB2TOKFX", ("", _("Path to FB2-KFX (Kindle) converter program"))),
        ("EOPDS_FB2TOPDF", ("", _("Path to FB2-PDF converter program"))),
        ("EOPDS_FB2TOTXT", ("", _("Path to FB2-TXT converter program"))),
        ("EOPDS_FB2TOMD", ("", _("Path to FB2-Markdown converter program"))),
        (
            "EOPDS_TEMP_DIR",
            (os.path.join(BASE_DIR, "tmp"), _("Path to temporary files directory")),
        ),
        (
            "EOPDS_SERVER_LOG",
            (
                os.path.join(BASE_DIR, "opds_catalog/log/eopds_server.log"),
                _("Path to logfile for eopds_server process"),
            ),
        ),
        (
            "EOPDS_SCANNER_LOG",
            (
                os.path.join(BASE_DIR, "opds_catalog/log/eopds_scanner.log"),
                _("Path to logfile for eopds_scanner process"),
            ),
        ),
        (
            "EOPDS_TELEBOT_LOG",
            (
                os.path.join(BASE_DIR, "opds_catalog/log/eopds_telebot.log"),
                _("Path to logfile for eopds_telebot process"),
            ),
        ),
        (
            "EOPDS_SERVER_PID",
            (
                os.path.join(BASE_DIR, "opds_catalog/tmp/eopds_server.pid"),
                _("Path to pidfile for eopds_server process"),
            ),
        ),
        (
            "EOPDS_SCANNER_PID",
            (
                os.path.join(BASE_DIR, "opds_catalog/tmp/eopds_scanner.pid"),
                _("Path to pidfile for eopds_scanner process"),
            ),
        ),
        (
            "EOPDS_TELEBOT_PID",
            (
                os.path.join(BASE_DIR, "opds_catalog/tmp/eopds_telebot.pid"),
                _("Path to pidfile for eopds_telebot process"),
            ),
        ),
    ]
)

CONSTANCE_CONFIG_FIELDSETS = {
    "1. General Options": (
        "EOPDS_LANGUAGE",
        "EOPDS_ROOT_LIB",
        "EOPDS_BOOK_EXTENSIONS",
        "EOPDS_CACHE_TIME",
        "EOPDS_SCAN_START_DIRECTLY",
    ),
    "2. Server Options": (
        "EOPDS_AUTH",
        "EOPDS_ALPHABET_MENU",
        "EOPDS_DOUBLES_HIDE",
        "EOPDS_COVER_SHOW",
        "EOPDS_SPLITITEMS",
        "EOPDS_MAXITEMS",
        "EOPDS_TITLE_AS_FILENAME",
        "EOPDS_NOCOVER_PATH",
    ),
    "3. Scanner Options": (
        "EOPDS_FB2SAX",
        "EOPDS_ZIPSCAN",
        "EOPDS_ZIPCODEPAGE",
        "EOPDS_INPX_ENABLE",
        "EOPDS_INPX_SKIP_UNCHANGED",
        "EOPDS_INPX_TEST_ZIP",
        "EOPDS_INPX_TEST_FILES",
        "EOPDS_DELETE_LOGICAL",
    ),
    "4. Scanner Shedule": (
        "EOPDS_SCAN_SHED_MIN",
        "EOPDS_SCAN_SHED_HOUR",
        "EOPDS_SCAN_SHED_DAY",
        "EOPDS_SCAN_SHED_DOW",
    ),
    "5. Telegramm Bot Options": (
        "EOPDS_TELEBOT_API_TOKEN",
        "EOPDS_TELEBOT_AUTH",
        "EOPDS_TELEBOT_MAXITEMS",
    ),
    "6. Converters Options": (
        "EOPDS_FB2TOEPUB", "EOPDS_FB2TOEPUB3", "EOPDS_FB2TOKEPUB",
        "EOPDS_FB2TOMOBI", "EOPDS_FB2TOKFX", "EOPDS_FB2TOPDF",
        "EOPDS_FB2TOTXT", "EOPDS_FB2TOMD", "EOPDS_TEMP_DIR",
    ),
    "7. Log & PID Files": (
        "EOPDS_SERVER_LOG",
        "EOPDS_SCANNER_LOG",
        "EOPDS_TELEBOT_LOG",
        "EOPDS_SERVER_PID",
        "EOPDS_SCANNER_PID",
        "EOPDS_TELEBOT_PID",
    ),
}
