# Generated by Django 5.1.15 on 2026-06-21 07:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opds_catalog', '0005_auto_20161204_2138'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cfi', models.CharField(blank=True, default='', max_length=512, verbose_name='CFI position')),
                ('percentage', models.FloatField(default=0.0, verbose_name='Reading progress (%)')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last read')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opds_catalog.book', verbose_name='Book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bookmark',
                'verbose_name_plural': 'Bookmarks',
                'unique_together': {('user', 'book')},
            },
        ),
    ]
