class Mimetype:
    OCTET_STREAM = 'application/octet-stream'
    XML = 'application/xml'
    ZIP = 'application/zip'

    EPUB = 'application/epub+zip'
    EPUB3 = 'application/epub+zip'
    KEPUB = 'application/kepub+zip'
    FB2 = 'application/fb2+xml'
    FB2_ZIP = 'application/fb2+zip'
    PDF = 'application/pdf'
    MSWORD = 'application/msword'
    MOBI = 'application/x-mobipocket-ebook'
    KFX = 'application/x-kfx'
    DJVU = 'image/vnd.djvu'
    TEXT = 'text/plain'
    MD = 'text/markdown'
    RTF = 'text/rtf'
